// This file is generated by kconfig_compiler from panaxinecfg.kcfg.
// All changes you do to this file will be lost.

#include "xinecfg.h"

#include <kstaticdeleter.h>

XineCfg *XineCfg::mSelf = 0;
static KStaticDeleter<XineCfg> staticXineCfgDeleter;

XineCfg *XineCfg::self()
{
  if ( !mSelf ) {
    staticXineCfgDeleter.setObject( mSelf, new XineCfg() );
    mSelf->readConfig();
  }

  return mSelf;
}

XineCfg::XineCfg(  )
  : KConfigSkeleton( QString::fromLatin1( "panarc" ) )
{
  mSelf = this;
  setCurrentGroup( QString::fromLatin1( "Xine-Engine" ) );

  KConfigSkeleton::ItemString  *itemOutputPlugin;
  itemOutputPlugin = new KConfigSkeleton::ItemString( currentGroup(), QString::fromLatin1( "Output Plugin" ), mOutputPlugin, QString::fromLatin1( "auto" ) );
  addItem( itemOutputPlugin, QString::fromLatin1( "OutputPlugin" ) );
  KConfigSkeleton::ItemBool  *itemCustomDevice;
  itemCustomDevice = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "Custom Device" ), mCustomDevice, false );
  addItem( itemCustomDevice, QString::fromLatin1( "CustomDevice" ) );
}

XineCfg::~XineCfg()
{
  if ( mSelf == this )
    staticXineCfgDeleter.setObject( mSelf, 0, false );
}

