// This file is generated by kconfig_compiler from panaxinecfg.kcfg.
// All changes you do to this file will be lost.
#ifndef XINECFG_H
#define XINECFG_H

#include <kconfigskeleton.h>
#include <kdebug.h>

class XineCfg : public KConfigSkeleton
{
  public:

    static XineCfg *self();
    ~XineCfg();

    /**
      Set Sound output method to use
    */
    static
    void setOutputPlugin( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "OutputPlugin" ) ))
        self()->mOutputPlugin = v;
    }

    /**
      Get Sound output method to use
    */
    static
    QString outputPlugin()
    {
      return self()->mOutputPlugin;
    }

    /**
      Set Enable a custom device
    */
    static
    void setCustomDevice( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "CustomDevice" ) ))
        self()->mCustomDevice = v;
    }

    /**
      Get Enable a custom device
    */
    static
    bool customDevice()
    {
      return self()->mCustomDevice;
    }

    static
    void writeConfig()
    {
      static_cast<KConfigSkeleton*>(self())->writeConfig();
    }
  protected:
    XineCfg();
    static XineCfg *mSelf;


    // Xine-Engine
    QString mOutputPlugin;
    bool mCustomDevice;

  private:
};

#endif

